### ISSUE TITLE
xin file glove_no_tok.txt 

### ISSUE THREAD

**Issue by trinh-hoang-hiep** [vudat1710/QAVN#1]
Em có thể xin file glove_no_tok.txt  được không ạ

**Comment by vudat1710** [comment]
https://drive.google.com/file/d/1-0DAHz35FTirz6aMHqMvwimMO7IcCEpf/view
Mình không nhớ file này có phải tách từ hay không. Bạn kiểm tra nhé

**Comment by trinh-hoang-hiep** [comment]
em cảm ơn anh ạ


Vào Th 5, 28 thg 5, 2020 vào lúc 08:24 Vũ Tiến Đạt <
notifications@github.com> đã viết:
